Fixed right-left flip if template is not RPI and other minor improvements (#3305)
* Added test to catch #3300

* Moved code into new add_orthogonal_label() function

* Systematically reorient the image before creating the label

Fixes #3300

* No more hard-coding of the disc label file.

Fixes #3322

* Updated URL for sct_testing_data

Related to:
- https://github.com/sct-data/sct_testing_data/issues/6
- https://github.com/sct-data/sct_testing_data/issues/7

* Added test for non-RPI template

Related to #3300

* Added test test_sct_register_to_template_non_rpi_data()

* Clarified usage with ldisc and -ref subject

Fixed #3306

* Fixed issue if info_label.txt does not include id_label=10

This could happen for custom templates

* Fixed variable referenced before assignment bug

UnboundLocalError: local variable 'file_template_disc_labeling' referenced before assignment

* sct_register_to_template.py: Fix 'reference before assignment' bug

* Remove fname_template_disc_labeling
* Replace "elif label_type == 'vert'" with 'else' to match previous usage (prior to PR)

* Turn template_lpi into a fixture

* Use list for 'argv' instead of string + .split()

* Fix bug by returning str path for template_lpi fixture

* Clarified usage for -ldisc

Fixed #3323

* Update spinalcordtoolbox/scripts/sct_register_to_template.py

Co-authored-by: Joshua Newton <joshuacwnewton@gmail.com>

Co-authored-by: Joshua Newton <joshuacwnewton@gmail.com>