install: workaround package installation failures using conda3
- install numpy before requirements
- workaround dipy package missing nibabel dependency

  RuntimeError: Need nisext package from nibabel installation - please
  install nibabel first

- don't abort on missing py3k conda/pip packages for now
- split/lax pip requirement sets for py3k


Former-commit-id: a3deff4388ab04623b5da57cbea3ba805cf13362