Replace `libglib2.0-0` with `t64` version to fix Debian Rolling Release test failure (#4463)
## Description
<!-- describe what the PR is about. Explain the approach and possible
drawbacks.It's ok to repeat some text from the related issue. -->

Currently, we manually install the old `libglib2.0-0`, which appears to
cause a conflict with the new `libglib2.0-0t64`. My best guess is that
one of the other packages that we install (e.g. `gcc`/`git`/`curl`/etc.)
had upgraded to `libglib2.0-0t64`, so by simultaneously installing the
old package, we run into:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Unsatisfied dependencies:
 libglib2.0-0t64 : Breaks: libglib2.0-0 (< 2.78.4-7~)
Error: Unable to correct problems, you have held broken packages.
```

## Linked issues

Fixes #4452.