Avoid nibabel crashes due to `int64` arrays by explicitly passing `dtype`/`header` to `Nifti1Image` (#4433)
nibabel will throw an error for instances of `Nifti1Image(data, affine)`
when data is of type int64 (and no header/dtype arguments are specified):

```
ValueError: """Image data has type int64, which may cause incompatibilities with other tools. 
               To use this type, pass an explicit header or dtype argument to Nifti1Image()."""
```