Drop support for 2014-era Linux.
Merging pytorch (6aa1f4e) caused
> OSError: dlopen: cannot load any more object with static TLS

on Debian 8 and Ubuntu Trusty.

This is a known issue with pytorch, see e.g.
https://github.com/pytorch/pytorch/issues/2083
https://github.com/scikit-learn/scikit-learn/issues/14485
https://github.com/pytorch/pytorch/issues/2575
https://stackoverflow.com/questions/14892101/cannot-load-any-more-object-with-static-tls

Apparently there might be a workaround involving reordering
import statements, but the root issue is that pytorch doesn't get testing
on "obscure" platforms. Including pytorch means we can't reliably support
them.