Pin onnxruntime version to fix "ImportError: cannot import name 'get_all_providers'" for macOS in CI (#2931)
* requirements.txt: Pin onnxruntime version

Onnxruntime got a version bump that breaks our macOS
Mojave CI build.

* requirements.txt: Specify sys_platform, add comment

* requirements.txt: remove redundant line

Co-authored-by: Alexandru Jora <alexandru@jora.ca>