install: workaround package installation failures using conda3
- install numpy before requirements
- workaround dipy package missing nibabel dependency

  RuntimeError: Need nisext package from nibabel installation - please
  install nibabel first

- don't abort on missing py3k conda/pip packages for now
- split/lax pip requirement sets for py3k


Former-commit-id: 05732d9563e1fcc7abac7a9a9eb85151830e2c08 [formerly 1b7de7b122595f0e070e46742d44bf6211da2bc0 [formerly a3deff4388ab04623b5da57cbea3ba805cf13362]]
Former-commit-id: 9056988b18e7460f36742d78b2b5e984995e480c
Former-commit-id: 1cc84d1968cf65f60600bb00c8b31a115d77cb5d