install: workaround package installation failures using conda3
- install numpy before requirements
- workaround dipy package missing nibabel dependency

  RuntimeError: Need nisext package from nibabel installation - please
  install nibabel first

- don't abort on missing py3k conda/pip packages for now
- split/lax pip requirement sets for py3k