`qc2.py`: Fix bug by using tuple instead of list of `slice` objs
Was getting the following error:

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices