`sct_analyze_texture`: Remove tmp file in between reorientations
Without doing this, on Windows machines, the following error is thrown:

    FileExistsError: [WinError 183] Cannot create a file when that file already exists

I don't think the intermediate file is used for anything, so I think this is OK to do.